id: A81767995
title: 'Wellspring of Bounty for the Fortunate: A Guru Yoga of the Three Family Lords'
type: translation
pechas:
- I74292556
- IB1BF84B8
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:16.720126
  last_modified_at: 2023-01-04 11:33:16.720138
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I74292556/20B0: EAFD
  IB1BF84B8/622F: EAFD
